# SPDX-FileCopyrightText: 2020-2025 Laurent Montel <montel@kde.org>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/cppcheck.yml
      - /gitlab-templates/craft-windows-x86-64-qt6.yml
      - /gitlab-templates/craft-windows-appx-qt6.yml
      - /gitlab-templates/craft-macos-arm64-qt6.yml
      - /gitlab-templates/craft-macos-x86-64-qt6.yml
      - /gitlab-templates/craft-appimage-qt6.yml
      - /gitlab-templates/alpine-qt6.yml
      - /gitlab-templates/linux-qt6-next.yml
      - /gitlab-templates/pre-commit.yml
      - /gitlab-templates/documentation.yml
